
/// If a player KILL THE MASTER, the horde is defeated, the other zombies disappear and the horde will spawn in another place

string theHordeMasterName_Day 	= "ZmbM_DH_Master_Day"; 	// used at day time
string theHordeMasterName_Night = "ZmbM_DH_Master_Night"; 	// used at night time (if "50" is set to 1 in the json file)

// MASTER is used to lead the horde to hunt the players
// The default Masters have a very good hear so he can hunt player at long distance (300-400m) and he have a lot of health points
// When the horde is defeated the player can loot the Master

/// !!BUG!! If you use PvZmoD Tweaked Zombies :
/// When the Master is killed, 
/// the player have to shoot a last time on the dead body with a fire weapon 
/// to access the zombie inventory



// List of class of zombies that can spawn in the dark horde during day time
ref TStringArray zombiesListDayTime = {
	"ZmbM_RCZ_HermitSkinny_Beige",
	"ZmbM_RCZ_HermitSkinny_Black",
	"ZmbM_RCZ_HermitSkinny_Green",
	"ZmbM_RCZ_HermitSkinny_Red",
	"ZmbM_RCZ_FarmerFat_Beige",
	"ZmbM_RCZ_FarmerFat_Blue",
	"ZmbM_RCZ_FarmerFat_Brown",
	"ZmbM_RCZ_FarmerFat_Green",
	"ZmbF_RCZ_CitizenANormal_Beige",
	"ZmbF_RCZ_CitizenANormal_Brown",
	"ZmbF_RCZ_CitizenANormal_Blue",
	"ZmbM_RCZ_CitizenASkinny_Blue",
	"ZmbM_RCZ_CitizenASkinny_Brown",
	"ZmbM_RCZ_CitizenASkinny_Grey",
	"ZmbM_RCZ_CitizenASkinny_Red",
	"ZmbM_RCZ_CitizenBFat_Blue",
	"ZmbM_RCZ_CitizenBFat_Red",
	"ZmbM_RCZ_CitizenBFat_Green",
	"ZmbF_RCZ_CitizenBSkinny",
	"ZmbM_RCZ_PrisonerSkinny",
	"ZmbM_RCZ_FirefighterNormal",
	"ZmbM_RCZ_FishermanOld_Blue",
	"ZmbM_RCZ_FishermanOld_Green",
	"ZmbM_RCZ_FishermanOld_Grey",
	"ZmbM_RCZ_FishermanOld_Red",
	"ZmbM_RCZ_JournalistSkinny",
	"ZmbF_RCZ_JournalistNormal_Blue",
	"ZmbF_RCZ_JournalistNormal_Green",
	"ZmbF_RCZ_JournalistNormal_Red",
	"ZmbF_RCZ_JournalistNormal_White",
	"ZmbM_RCZ_ParamedicNormal_Blue",
	"ZmbM_RCZ_ParamedicNormal_Green",
	"ZmbM_RCZ_ParamedicNormal_Red",
	"ZmbM_RCZ_ParamedicNormal_Black",
	"ZmbF_RCZ_ParamedicNormal_Blue",
	"ZmbF_RCZ_ParamedicNormal_Green",
	"ZmbF_RCZ_ParamedicNormal_Red",
	"ZmbM_RCZ_HikerSkinny_Blue",
	"ZmbM_RCZ_HikerSkinny_Green",
	"ZmbM_RCZ_HikerSkinny_Yellow",
	"ZmbF_RCZ_HikerSkinny_Blue",
	"ZmbF_RCZ_HikerSkinny_Grey",
	"ZmbF_RCZ_HikerSkinny_Green",
	"ZmbF_RCZ_HikerSkinny_Red",
	"ZmbM_RCZ_HunterOld_Autumn",
	"ZmbM_RCZ_HunterOld_Spring",
	"ZmbM_RCZ_HunterOld_Summer",
	"ZmbM_RCZ_HunterOld_Winter",	
	"ZmbF_RCZ_SurvivorNormal_Blue",
	"ZmbF_RCZ_SurvivorNormal_Orange",
	"ZmbF_RCZ_SurvivorNormal_Red",
	"ZmbF_RCZ_SurvivorNormal_White",
	"ZmbM_RCZ_PolicemanFat",
	"ZmbF_RCZ_PoliceWomanNormal",
	"ZmbM_RCZ_PolicemanSpecForce",
	"ZmbM_RCZ_SoldierNormal",
	"ZmbM_RCZ_usSoldier_normal_Woodland",
	"ZmbM_RCZ_usSoldier_normal_Desert",
	"ZmbM_RCZ_CommercialPilotOld_Blue",
	"ZmbM_RCZ_CommercialPilotOld_Olive",
	"ZmbM_RCZ_CommercialPilotOld_Brown",
	"ZmbM_RCZ_CommercialPilotOld_Grey",
	"ZmbM_RCZ_PatrolNormal_PautRev",
	"ZmbM_RCZ_PatrolNormal_Autumn",
	"ZmbM_RCZ_PatrolNormal_Flat",
	"ZmbM_RCZ_PatrolNormal_Summer",
	"ZmbM_RCZ_JoggerSkinny_Blue",
	"ZmbM_RCZ_JoggerSkinny_Green",
	"ZmbM_RCZ_JoggerSkinny_Red",
	"ZmbF_RCZ_JoggerSkinny_Blue",
	"ZmbF_RCZ_JoggerSkinny_Brown",
	"ZmbF_RCZ_JoggerSkinny_Green",
	"ZmbF_RCZ_JoggerSkinny_Red",
	"ZmbM_RCZ_MotobikerFat_Beige",
	"ZmbM_RCZ_MotobikerFat_Black",
	"ZmbM_RCZ_MotobikerFat_Blue",
	"ZmbM_RCZ_VillagerOld_Blue",
	"ZmbM_RCZ_VillagerOld_Green",
	"ZmbM_RCZ_VillagerOld_White",
	"ZmbM_RCZ_SkaterYoung_Blue",
	"ZmbM_RCZ_SkaterYoung_Brown",
	"ZmbM_RCZ_SkaterYoung_Green",
	"ZmbM_RCZ_SkaterYoung_Grey",
	"ZmbF_RCZ_SkaterYoung_Brown",
	"ZmbF_RCZ_SkaterYoung_Striped",
	"ZmbF_RCZ_SkaterYoung_Violet",
	"ZmbF_RCZ_DoctorSkinny",
	"ZmbF_RCZ_BlueCollarFat_Blue",
	"ZmbF_RCZ_BlueCollarFat_Green",
	"ZmbF_RCZ_BlueCollarFat_Red",
	"ZmbF_RCZ_BlueCollarFat_White",
	"ZmbF_RCZ_MechanicNormal_Beige",
	"ZmbF_RCZ_MechanicNormal_Green",
	"ZmbF_RCZ_MechanicNormal_Grey",
	"ZmbF_RCZ_MechanicNormal_Orange",
	"ZmbM_RCZ_MechanicSkinny_Blue",
	"ZmbM_RCZ_MechanicSkinny_Grey",
	"ZmbM_RCZ_MechanicSkinny_Green",
	"ZmbM_RCZ_MechanicSkinny_Red",
	"ZmbM_RCZ_ConstrWorkerNormal_Beige",
	"ZmbM_RCZ_ConstrWorkerNormal_Black",
	"ZmbM_RCZ_ConstrWorkerNormal_Green",
	"ZmbM_RCZ_ConstrWorkerNormal_Grey",
	"ZmbM_RCZ_HeavyIndustryWorker",
	"ZmbM_RCZ_OffshoreWorker_Green",
	"ZmbM_RCZ_OffshoreWorker_Orange",
	"ZmbM_RCZ_OffshoreWorker_Red",
	"ZmbM_RCZ_OffshoreWorker_Yellow",
	"ZmbF_RCZ_NurseFat",
	"ZmbM_RCZ_HandymanNormal_Beige",
	"ZmbM_RCZ_HandymanNormal_Blue",
	"ZmbM_RCZ_HandymanNormal_Green",
	"ZmbM_RCZ_HandymanNormal_Grey",
	"ZmbM_RCZ_HandymanNormal_White",
	"ZmbM_RCZ_DoctorFat",
	"ZmbM_RCZ_Jacket_beige",
	"ZmbM_RCZ_Jacket_black",
	"ZmbM_RCZ_Jacket_blue",
	"ZmbM_RCZ_Jacket_bluechecks",
	"ZmbM_RCZ_Jacket_brown",
	"ZmbM_RCZ_Jacket_greenchecks",
	"ZmbM_RCZ_Jacket_grey",
	"ZmbM_RCZ_Jacket_khaki",
	"ZmbM_RCZ_Jacket_magenta",
	"ZmbM_RCZ_Jacket_stripes",
	"ZmbF_RCZ_PatientOld",
	"ZmbM_RCZ_PatientSkinny",
	"ZmbF_RCZ_ShortSkirt_beige",
	"ZmbF_RCZ_ShortSkirt_black",
	"ZmbF_RCZ_ShortSkirt_brown",
	"ZmbF_RCZ_ShortSkirt_green",
	"ZmbF_RCZ_ShortSkirt_grey",
	"ZmbF_RCZ_ShortSkirt_checks",
	"ZmbF_RCZ_ShortSkirt_red",
	"ZmbF_RCZ_ShortSkirt_stripes",
	"ZmbF_RCZ_ShortSkirt_white",
	"ZmbF_RCZ_ShortSkirt_yellow",
	"ZmbF_RCZ_VillagerOld_Blue",
	"ZmbF_RCZ_VillagerOld_Green",
	"ZmbF_RCZ_VillagerOld_Red",
	"ZmbF_RCZ_VillagerOld_White",
	"ZmbF_RCZ_MilkMaidOld_Beige",
	"ZmbF_RCZ_MilkMaidOld_Black",
	"ZmbF_RCZ_MilkMaidOld_Green",
	"ZmbF_RCZ_MilkMaidOld_Grey",
	"ZmbM_RCZ_priestPopSkinny",
	"ZmbM_RCZ_ClerkFat_Brown",
	"ZmbM_RCZ_ClerkFat_Grey",
	"ZmbM_RCZ_ClerkFat_Khaki",
	"ZmbM_RCZ_ClerkFat_White",
	"ZmbF_RCZ_Clerk_Normal_Blue",
	"ZmbF_RCZ_Clerk_Normal_White",
	"ZmbF_RCZ_Clerk_Normal_Green",
	"ZmbF_RCZ_Clerk_Normal_Red",
	"ZmbF_RCZ_ClerkFat_Black",
	"ZmbF_RCZ_ClerkFat_GreyPattern",
	"ZmbF_RCZ_ClerkFat_BluePattern",
	"ZmbF_RCZ_ClerkFat_White"
};	

// List of class of zombies that can spawn in the dark horde during night time (if "50" is set to 1 in the json file. If set to 0, day zombies will always spawn)
ref TStringArray zombiesListNightTime = {
	"ZmbF_DH_WhiteLady",
	"ZmbF_DH_WhiteLady",
	"ZmbF_DH_WhiteLady",
	"ZmbF_DH_WhiteLady",
	
	"ZmbM_DH_Invisible_Guillie",
	"ZmbM_DH_Invisible_Guillie",
	"ZmbM_DH_Invisible_Guillie",
	"ZmbM_DH_Invisible_Guillie",
	"ZmbM_DH_Invisible_Guillie",
	"ZmbM_DH_Invisible_Guillie",

	"ZmbM_DH_NightWalker",
	"ZmbM_DH_NightWalker",
	"ZmbM_DH_NightWalker",
	"ZmbM_DH_NightWalker",

	"ZmbM_DH_Invisible_RedEye",
	"ZmbM_DH_Invisible_RedEye",
	"ZmbM_DH_Invisible_RedEye",
	
/// PSR2
///Sprinter=====	
	 // "PSR2_ZmbM_Murder_FastZMB",		
	 // "PSR2_ZmbM_Golovastik",
	 // "PSR2_ZmbM_Plague",
	 // "PSR2_ZmbM_krovosos", 	
	 // "PSR2_ZmbM_krovosos_black",
///Hard=========
	 // "PSR2_ZmbM_Kleshna",
	 // "PSR2_ZmbM_Zubastik",		
	 // "PSR2_ZmbM_Zubastik1",		
	 // "PSR2_ZmbM_Zubastik2",		
///Medium=======
	 // "PSR2_ZmbM_Mymia_SlowZMB",  		
	 // "PSR2_ZmbM_Tank1_BigZMB",//  (скоро)		
	 // "PSR2_ZmbM_BioHazardZMB",//  (скоро)						
	 // "PSR2_ZmbM_ZombieCivil",// 	 (скоро)
	 
// Be careful Chemlights are resource consuming for clients
	// "Chemlight_Red",
	// "Chemlight_Yellow",
	// "Chemlight_Blue",
	// "Chemlight_Green",
	// "Chemlight_White",
};	

